name: Ruby

on: [push, pull_request]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Testy
      run: |
        gem install bundler
        export HOMEBREW_NO_AUTO_UPDATE=1
        brew tap kashaiahyah85/homebrew-cask
        cd "$(brew --repository)"/Library/Taps/homebrew/homebrew-cask
        brew cask audit time-to-leave --download
        brew cask install time-to-leave
        brew cask uninstall time-to-leave 
