name: time-to-leave

on: [push, pull_request]

jobs:
  test:

    runs-on: macOS-latest

    steps:
    - name: tapping k85-tap
      run: |
        export HOMEBREW_NO_AUTO_UPDATE=1
        brew tap kashaiahyah85/homebrew-k85-tap
        cd "$(brew --repository)"/Library/Taps/kashaiahyah85/homebrew-k85-tap
        
    - name: install time-to-leave
      run: brew cask install time-to-leave
    
    - name: uninstall time-to-leave
        brew cask uninstall time-to-leave
